language: python
sudo: required
dist: trusty

python:
    - '2.7'
    - '3.5'
    - '3.6'

install:
    - pip install .
    - pip install nose2

script:
    - cd tests
    - nose2
    - cd ..

deploy:
    provider: pypi
    user: mmatl
    on:
        tags: true
        branch: master
    password:
        secure: TdW1HmmOmvt0M/5Z7x8IvD7qZ9McFoax7LqFK2JpvIx5m1P0S1mOLkLSnvR6noD5JQBiRFz0+LZC6QWbvndH2SFnl5RRDSvJP+PabcMxwG33XNLjfgweaoa3wIH+PVNRU09XBTnkT52w8Zcu9x615r9V5JPjhl2lARHqzKC+cX/vOelaDXlROcis4OkExTaFIzt+1SMksKe3FlW7jcEnHfbx1TbghWpDQALCitfdB2cQwk3xBZ227Ywa/O9p5d46nTv5LHWOYwlODfWYtAPjz7V2WT5Yp7MYuc5LdSO5urTyHvJdzmUHC33yfEzuzIoRv66DJ7JDole8Mdxy8sv/jQ8acW3+PFgit1LI+bbGK7CP5W2ZXXpKoX7Vg7n00aJU07C+0WsV0V4w0Daez4xYdTYglP46YBmoGeIFtDDjA7KQttf7X2NRvzF1wW6VMYRIif4Um4o8jmZyJ429a4WhmraAhPjPetqDTiYQSuSEb1bf9/9xbSL7T5paKxC/dFYpuljTVQFT3r+Z9TqZNtF3YzyU12x7Vp0w9Yt3sx8ZUnCYz/9qpOAQle0yL9Fw07tZ9/px2+5bMZZRL/8zBIWYXt4a3k9Oo3VwI8hzRYNeomtAyC3wTSIFvtFFpejKRMr6oFLagrlbBAsTx1ZrE4ZQ16L63gCRhN/crR5rYf4FcCE=

notifications:
    email: false
